{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "helmfile.fullname" . }}-tls
spec:
  secretName: {{ include "helmfile.fullname" . }}-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  dnsNames:
    - {{ .Values.ingress.hosts.host }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  email:
    - {{ .Values.certManager.email }}
{{- end }}
